apiVersion: v1
kind: Pod
metadata:
  name: use-configmap
  namespace: k8sdemo-namespace
spec:
  containers:
    - name: use-configmap-container
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 120"]
      volumeMounts:
        - name: configmap-volumes
          mountPath: "/config-volume"
          readOnly: true
  volumes:
    - name: configmap-volumes
      configMap:
        name: bootstrap-configmap
