apiVersion: v1
kind: Pod
metadata:
  name: k8sdemo-pod
  namespace: k8sdemo-namespace
spec:
  containers:
  - image: k8sdemo:v1
    name: k8sdemo-container
    ports:
    - containerPort: 8088
      hostPort: 8088
  restartPolicy: Always