apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  namespace: k8sdemo-namespace
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    hostPath:
      path: /Users/ls/k8s-volums/host-path
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: busybox-container
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /nginx-data
    command: ["/bin/sh", "-c"]
    args: ["echo Hello from the busybox container > /nginx-data/index.html;sleep 3600"]