apiVersion: v1
kind: Pod
metadata:
  name: share-host
  namespace: k8sdemo-namespace
spec:
  hostNetwork: true
  hostIPC: true
  hostPID: true
  containers:
  - name: busybox-shell
    image: busybox
    stdin: true
    tty: true