apiVersion: v1
kind: Pod
metadata:
  name: lifecircle
  namespace: k8sdemo-namespace
spec:
  containers:
    - name: busybox-lifecircle
      image: busybox
      command: ["/bin/sh", "-c"]
      args: ["sleep 3600"]
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "touch /var/1.txt"]
        preStop:
          exec:
            command: ["/bin/sh", "-c", "rm -rf /var/1.txt"]