apiVersion: batch/v1
kind: Job
metadata:
  name: sleep-job
  namespace: k8sdemo-namespace
spec:
  template:
    spec:
      containers:
      - name: sleep-job-container
        image: busybox
        command: ["sh", "-c", "sleep 30"]
      restartPolicy: Never
  backoffLimit: 5 # 当任务失败时重新创建 pod 重试的最大次数
  activeDeadlineSeconds: 60 # 任务的最大运行时间
