apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cronJob-job
  namespace: k8sdemo-namespace
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronJob-job-container
            image: busybox
            command: ["sh", "-c", "sleep 5"]
          restartPolicy: Never