apiVersion: v1
kind: Pod
metadata:
  name: use-secret
  namespace: k8sdemo-namespace
spec:
  containers:
    - name: use-secret-container
      image: busybox
      args:
        - sleep
        - "120"
      volumeMounts:
        - name: secret-cred
          mountPath: "/secret-volume"
          readOnly: true
  volumes:
    - name: secret-cred
      secret:
        secretName: test-secret
