apiVersion: v1
kind: Pod
metadata:
  name: test-downwardapi
  namespace: k8sdemo-namespace
  labels:
    a: a1
    b: b2
    c: c3
spec:
  containers:
    - name: busybox-container
      image: busybox
      tty: true
      stdin: true
      volumeMounts:
        - name: podinfo
          mountPath: /etc/podinfo
          readOnly: false
  volumes:
    - name: podinfo
      projected:
        sources:
          - downwardAPI:
              items:
                - path: "labels"
                  fieldRef:
                    fieldPath: metadata.labels