apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: caches.stable.example.com
spec:
  group: stable.example.com
  names:
    kind: Cache
    listKind: CacheList
    plural: caches
    singular: cache
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              type: object
              properties:
                memory:
                  type: string
                sharding:
                  type: integer
                region:
                  type: string
                az:
                  type: string
          type: object
      served: true
      storage: true
