apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: k8sdemo-namespace
  labels:
    app: biz
spec:
  ports:
    - port: 8081
      targetPort: 8088
      name: web
  selector:
    app: biz